import React from "react";

function About() {
    return (
        <div className="about">
            <div className="about-image"></div>
            <h1>Founded in 1818</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia necessitatibus sed dolor, odio harum alias reprehenderit nostrum debitis, optio, esse fugit. Neque, dolor praesentium! Neque cum saepe nam dicta dolores.</p>
        </div>
    );
}

export default About;